-- Create the new ones
CREATE LOGIN %bpmuser_username% WITH PASSWORD = '%bpmuser_password%'
GO

ALTER DATABASE [%dbname%] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [%dbname%] SET AUTO_UPDATE_STATISTICS_ASYNC ON
GO

ALTER DATABASE [%dbname%] SET ALLOW_SNAPSHOT_ISOLATION ON
GO

ALTER DATABASE [%dbname%] SET READ_COMMITTED_SNAPSHOT ON
GO

ALTER DATABASE [%dbname%] SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 2 DAYS, AUTO_CLEANUP = ON)
GO