apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpm-deployment
  namespace: bpm
spec:
  selector:
    matchLabels:
       app: bpm
  replicas: 1
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: bpm
        tier: backend
    spec:
      hostAliases:
        - ip: "40.78.225.32"
          hostnames:
            - "bpm-postgres"
        - ip: "137.135.74.160"
          hostnames:
            - "bpm-apacheds"
      containers:
      - name: bpm
        # Run this image
        image: mpmbpmecr.azurecr.io/bpm/runtime:5.3.0
        #resources:
        #  requests:
        #    cpu: 200m
        #livenessProbe:
        #  httpGet:
        #    path: /bpm/adapter/v1/liveness
        #    port: 8282
        #  initialDelaySeconds: 60
        #  periodSeconds: 30
        #  timeoutSeconds: 2
        #  successThreshold: 1
        #  failureThreshold: 3
        #readinessProbe:
        #  httpGet:
        #    path: /bpm/adapter/v1/readiness
        #    port: 8282
        #  initialDelaySeconds: 60
        #  periodSeconds: 30
        #  timeoutSeconds: 2
        #  successThreshold: 1
        #  failureThreshold: 3
        ports:
          - containerPort: 8181
            hostPort: 8181
        env:
          - name: JDBC_DRIVERCLASS
            value: com.microsoft.sqlserver.jdbc.SQLServerDriver
          - name: JDBC_URL
            value: "jdbc:sqlserver://mmyburgh-aks-storage.database.windows.net:1433;database=bpm"
          - name: LDAP_SYSTEM_ALIAS
            value: "system"
          - name: LDAP_SYSTEM_URL
            value: "ldap://137.135.74.160:10389/ou=system"
          - name: LDAP_EASYAS_ALIAS
            value: "easyAs"
          - name: LDAP_EASYAS_URL
            value: "ldap://bpm-apacheds:10389/o=easyAsInsurance" 
        envFrom:
          - secretRef:
              name: bpm-secrets-db
          - secretRef:
              name: bpm-secrets-ldap            
      imagePullSecrets:
      - name: secret-bpme-acr
