apiVersion: v1
kind: Secret
metadata:
  name: bpm-secrets-db
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/resource-policy": keep
type: Opaque
data:
  ADMIN_USERNAME: {{ .Values.admin.username | required ".Values.admin.username is required" | b64enc }}
  ADMIN_PASSWORD: {{ .Values.admin.password | required ".Values.admin.password is required" | b64enc }}
  BPMUSER_USERNAME: {{ .Values.bpmuser.username | required ".Values.bpmuser.username is required" | b64enc }}
  BPMUSER_PASSWORD: {{ .Values.bpmuser.password | required ".Values.bpmuser.password is required" | b64enc }}
  DBNAME: {{ .Values.databaseName | required ".Values.databaseName is required" | b64enc }}
