apiVersion: v1
kind: Service
metadata:
  name: bpm-service
  namespace: {{ .Release.Namespace }}
  annotations: {}
spec:
  selector:
    app: bpm
    tier: backend
  ports:
  - protocol: TCP
    port: 8181
    targetPort: 8181
  type: ClusterIP
