apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bpm-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: letsencrypt-prod
    appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.bpmDomainName }}
    secretName: bpm-secret-tls
  rules:
  - host: {{ .Values.bpmDomainName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bpm-service
            port:
              number: 8181
