apiVersion: v1
kind: Secret
metadata:
  name: bpm-secrets-ldap-ssl-cert
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values }}
  {{- if and (hasPrefix "LDAP_" $key) (hasSuffix "_SSLCERT" $key) }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
