apiVersion: v1
kind: Secret
metadata:
  name: bpm-secrets-ldap
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values }}
  {{- if and (hasPrefix "LDAP_" $key) (or (hasSuffix "_PRINCIPAL" $key) (hasSuffix "_CREDENTIALS" $key)) }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
